## 参考情報
* [torch\.Tensor — PyTorch master documentation](https://pytorch.org/docs/master/tensors.html?highlight=torch%20tensor#torch.Tensor)
* [torch — PyTorch master documentation](https://pytorch.org/docs/master/torch.html#torch.tensor)

In [19]:
import torch

torch packageとは?

>The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful utilities.

## torch.Tensor の作り方

### Tensor の data type
* 多分 numpyと同じでtensorの要素は同じデータ型でないといけない。
* デフォルトはfloat32かな。設定もできる。
* float32, float64, uint8, int16, int32, int64, bool とある
* 参照
    * [Tensor Attributes — PyTorch master documentation](https://pytorch.org/docs/master/tensor_attributes.html#torch.torch.dtype)

In [20]:
# デフォルトはfloat32
torch.get_default_dtype()

torch.float32

In [22]:
float_tensor = torch.ones(5, dtype=torch.float)
float_tensor

tensor([1., 1., 1., 1., 1.])

In [24]:
int_tensor = torch.ones(3, dtype=torch.int)
int_tensor

tensor([1, 1, 1], dtype=torch.int32)

In [26]:
long_tensor = torch.ones(3, dtype=torch.long)
long_tensor

tensor([1, 1, 1])

In [28]:
bool_tensor = torch.ones(4, dtype=torch.bool)
bool_tensor

tensor([True, True, True, True])

In [29]:
int_zerodim = torch.tensor(1, dtype=torch.int)
int_zerodim

tensor(1, dtype=torch.int32)

#### tensorのdtypeを表示

In [30]:
long_tensor.dtype

torch.int64

### Tensorの作成

#### torch.tensor データを与えてTensorを作る
* torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor
* [torch.tensor — PyTorch master documentation](https://pytorch.org/docs/master/torch.html?highlight=torch%20tensor#torch.tensor)

In [34]:
torch.tensor([[0.11111, 0.222222, 0.3333333]], dtype=torch.float64)

tensor([[0.1111, 0.2222, 0.3333]], dtype=torch.float64)

In [35]:
torch.tensor([0, 1])  # Type inference on data

tensor([0, 1])

In [37]:
# ちなみにint64になっている
t = torch.tensor([0, 1])
t.dtype

torch.int64

In [38]:
torch.tensor(3.14159)  # Create a scalar (zero-dimensional tensor)

tensor(3.1416)

#### torch.randn 正規分布からTensor作成
* torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
* [torch.randn — PyTorch master documentation](https://pytorch.org/docs/master/torch.html?highlight=torch%20randn#torch.randn)

In [31]:
torch.randn(2)

tensor([0.3348, 0.4753])

In [32]:
torch.randn((2, 3))

tensor([[ 0.6649,  2.1062,  1.7357],
        [ 1.4921, -0.3653, -0.4585]])

#### torch.zeros
* torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
* [torch.zeros — PyTorch master documentation](https://pytorch.org/docs/master/torch.html?highlight=torch%20tensor#torch.zeros)

In [39]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#### torch.ones
* torch.ones(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
* [torch.ones — PyTorch master documentation](https://pytorch.org/docs/master/torch.html?highlight=torch%20tensor#torch.ones)

In [42]:
print(torch.ones(2, 3))
print(torch.ones(2, 3).dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


#### その他よく使いそうなもの
* torch.arange
* torch.linspace
* torch.eye (行列のIをつくる Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.)

In [43]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Tensorの演算

torch.Tensor にするといろんな演算が簡単にできる

### 転置

In [7]:
ts1 = torch.tensor([[1, 2], [3, 4]])
ts1

tensor([[1, 2],
        [3, 4]])

In [8]:
ts1.T

tensor([[1, 3],
        [2, 4]])

### 行列の積

### 行列の各要素に対する演算

#### 各要素のexpをとる

In [10]:
# 整数?Long型に対してはできない
ts1.exp()

RuntimeError: exp_vml_cpu not implemented for 'Long'

In [14]:
# 型の変更をしてからならできる
ts1 = ts1.float()
ts1.exp()

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]])

In [44]:
# こっちでもいいらしい
torch.exp(ts1)

tensor([[ 2.7183,  7.3891],
        [20.0855, 54.5982]])

#### logをとる

In [16]:
ts1.log()  # こちらもfloatでないとだめ

tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])

### 行列の行ごとに演算をする

In [45]:
# 形を行ごとに合わせる
torch.tensor([[1., 2., 3.], [4., 5., 6.]])/torch.tensor([[0.1], [10.]])

tensor([[10.0000, 20.0000, 30.0000],
        [ 0.4000,  0.5000,  0.6000]])

In [49]:
torch.tensor([[1., 2., 3.], [4., 5., 6.]]) * torch.tensor([[0.1], [10.]])

tensor([[ 0.1000,  0.2000,  0.3000],
        [40.0000, 50.0000, 60.0000]])

### 行列のいろんな方向の合計をとる
* 2次元だとデフォルトは全ての要素、引数1で行ごと、引数0で列ごとの合計

In [46]:
torch.tensor([[1., 2., 3.], [4., 5., 6.]]).sum()

tensor(21.)

In [47]:
torch.tensor([[1., 2., 3.], [4., 5., 6.]]).sum(1)

tensor([ 6., 15.])

In [48]:
torch.tensor([[1., 2., 3.], [4., 5., 6.]]).sum(0)

tensor([5., 7., 9.])